### ISSUE TITLE
PeepOpen doesn't register keybindings in Emacs

### ISSUE THREAD

**Issue by caleb** [topfunky/PeepOpen-Issues#110]
I'm using PeepOpen 0.2.1, with emacs 23.2.1 (from http://emacsformacosx.com/).

I installed the Emacs plugin, and I know it's working because I can manually run the peepopen-goto-file-gui function with M-x.

I am using the emacs-starter kit (http://github.com/technomancy/emacs-starter-kit) and I installed the TextMate.el plugin.

The problem seems to be that the peepopen-bind-keys hook isn't executing. If I manually specify they keybinding in my config file everything works:

```
(define-key *textmate-mode-map* [(super t)] 'peepopen-goto-file-gui)
```

The code I use to configure peepopen is:

```
(add-to-list 'load-path "~/.emacs.d/vendor/textmate.el")
(require 'textmate)
(textmate-mode)
(add-to-list 'load-path "~/.emacs.d/vendor/")
(require 'peepopen)
```

Any ideas? (PeepOpen rocks, BTW, I love that the source code came with it!)

**Comment by caleb** [comment]
By the way, I know textmate mode is enabled (I have "mate" in the mode status bar), but it seems to work if I exit and then enter textmate-mode:

```
M-x textmate-mode
M-x textmate-mode
```

If I do that, then command-T works.

**Comment by topfunky** [comment]
Some updates to the latest version of PeepOpen's configuration files should fix this (v0.2.2 or greater).

Run "Check for Updates" in PeepOpen, and re-install the Emacs plugin from PeepOpen's Preferences window.

I tried it in Emacs 23.2 and it worked with the standard Command-T.

Be sure to add this line to your configuration so it opens files in the same window:

   (setq ns-pop-up-frames nil)

**Comment by caleb** [comment]
Hmm, I did an update, and it still doesn't work. I'm using a stock emacs-starter-kit. I'll give it a try with your starter kit and tell you my results.

**Comment by caleb** [comment]
Okay, I used your starter kit, and it worked fine. Thanks

**Comment by milep** [comment]
I have this same issue with technomancy's starter kit (https://github.com/technomancy/emacs-starter-kit) in emacs 24
