### ISSUE TITLE
.rvmrc file breaks peepopen

### ISSUE THREAD

**Issue by austinthecoder** [topfunky/PeepOpen-Issues#140]
PeepOpen doesn't work for me when the project contains a '.rvmrc' file. See the screencast:

http://screencast.com/t/Y2U3ZDQ5N2It

**Comment by adzap** [comment]
I have the same problem. For projects without a .rvmrc, PeepOpen will read the list of files. If the .rvmrc file is present, then it gets stuck at 'Reading files...' and never completes. 

PeepOpen must then be restarted before it can work in a project dir without an .rvmrc file.

I am using MacVim v7.3(53) with PeepOpen 0.2.4. The same issus was occurring 0.2.3 but I could identify what the cause was until I saw this issue and tested it.

**Comment by lardawge** [comment]
Please fix this.

**Comment by fannar** [comment]
Really annoying. Love PeepOpen with TextMate though. Have tried to add .rvmrc to the file ignore list but doesn't help.

**Comment by lardawge** [comment]
Workaround for me on this was to uncheck "show metadata with files"... This means git info is gone though...

**Comment by BryanDonovan** [comment]
I'm seeing the same issue (0.2.4)

**Comment by topfunky** [comment]
Thanks for the useful screencast bug report. That is a crazy bug.

We just released 0.3.0 with a bunch of bugfixes. Try it out and see if it fixes this problem for you.

**Comment by austinthecoder** [comment]
fixes it for me

**Comment by shad** [comment]
I'm still seeing this issue in 0.3.0.  If I turn off git metadata, then everything is fine.  As soon as I turn it back on and kick off PeepOpen, I see the issue again.

**Comment by adzap** [comment]
Same here. It only works for me after turning off the git metadata.

**Comment by jxpx777** [comment]
Why was this issue closed? I'm still seeing the same behavior on 0.3.2. Just because there's a workaround doesn't mean it's not still an issue…

**Comment by topfunky** [comment]
I wasn't able to reproduce the bug, and some people reported that it was fixed. If you're still seeing, it, I'll try to reproduce the bug with the latest version.
