### ISSUE TITLE
All files open in new window in TextMate since 0.3.1 update

### ISSUE THREAD

**Issue by peburrows** [topfunky/PeepOpen-Issues#205]
Since updating to 0.3.1, all files open in a new window instead of in the project window. This is a major annoyance and is essentially making the plugin unusable.

**Comment by topfunky** [comment]
Try reinstalling the TextMate plugin from PeepOpen preferences, and re-start TextMate.

We fixed the TextMate plugin to work better with directories that have spaces in the filename. I'm not sure if this is what's causing the problem, but it could be related.

**Comment by peburrows** [comment]
I tried reinstalling the plugin & restarting TextMate, but it didn't seem to fix the issue. FWIW, the project I'm working in has no spaces in directory names (or filenames, for that matter).

**Comment by allieus** [comment]
I'm using version 0.3.2. I also encountered the same bug. I hope this bug is fixed soon.

**Comment by peburrows** [comment]
This appears to have been fixed in the latest version (0.3.4).

**Comment by anderssvendal** [comment]
Seems like the problem is back in 0.3.5

**Comment by topfunky** [comment]
I've also experienced this, but only with some TextMate projects. One appeared to be a case-sensitivity issue but I haven't been able to figure it out yet.

**Comment by glortho** [comment]
Having this problem too with 0.3.5 and multiple versions of TextMate (including 1.5.10). A shame not to be able to use it anymore. Please do advise of fixes!

**Comment by phoet** [comment]
i have the same issue with 0.3.5 and it looks like this is happening only for files that are located in a textmate ignored folder, but accessible through the peepopen-search.
